print("How to prevent low blood glucose levels?")
print("1. Always carry a sugary snack or drink with you, such as glucose tablets, a carton of fruit juice or some sweets.")
print("2. If you have a glucagon injection kit, always keep it with you.")
print("3. Do not skip meals.")
print("4. Be careful when drinking alcohol. Do not drink large amounts, check your blood sugar level regularly, and eat a carbohydrate snack afterwards.")
print("5. Be careful when exercising; eating a carbohydrate snack before exercise can help to reduce the risk of a hypo. If you take some types of diabetes medicine, your doctor may recommend you take a lower dose before or after doing intense exercise.")
print("6. Have a carbohydrate snack, such as toast, if your blood sugar level drops too low while you're asleep (nocturnal hypoglycaemia).")
print("7. If you keep getting a low blood sugar level, talk to your diabetes care team about things you can do to help prevent it.")
print("Source: NHS")

